gpu_type: a40-48gb-pcie
gpu_count: "{{ instance_size }}"
cpu_count: "{{ ( instance_size | int ) * 6 }}"
real_memory: "{{ (instance_size | int) * 58880 }}"
disk_count: "{{ instance_size }}"
threads_per_core: 2
