- name: Configure autofs
  ansible.builtin.import_role:
    name: autofs

- name: Mount /scratch/shared
  ansible.posix.mount:
    src: "{{ hostvars['slurm-nfs-node-0'].ansible_fqdn }}:/scratch/shared"
    path: /scratch/shared
    opts: rw,sync,soft
    state: mounted
    fstype: nfs
  when: "{{ (hostvars['slurm-nfs-node-0'].disk_count | int) > 0 }}"

- name: Mount /opt/slurm
  ansible.posix.mount:
    src: "{{ hostvars['slurm-nfs-node-0'].ansible_fqdn }}:/opt/slurm"
    path: /opt/slurm
    opts: ro,sync,soft
    state: mounted
    fstype: nfs

- name: Install 99-slurm.sh
  ansible.builtin.copy:
    src: 99-slurm.sh
    dest: /etc/profile.d/99-slurm.sh
    owner: root
    group: root
    mode: '0755'

- name: Install pmix dependencies
  ansible.builtin.apt:
    name: 
      - libevent-dev
      - libhwloc-dev

- name: Mount /opt/pmix
  ansible.posix.mount:
    src: "{{ hostvars['slurm-nfs-node-0'].ansible_fqdn }}:/opt/pmix"
    path: /opt/pmix
    opts: ro,sync,soft
    state: mounted
    fstype: nfs

- name: Install slurm conf
  ansible.builtin.import_role:
    name: slurm_conf

- name: Create plugstack.conf.d directory
  ansible.builtin.file:
    path: /etc/slurm/plugstack.conf.d
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0755'

- name: Link pyxis config
  ansible.builtin.file:
    src: /opt/slurm/share/pyxis/pyxis.conf
    dest: /etc/slurm/plugstack.conf.d/pyxis.conf
    owner: root
    group: root
    state: link
