- name: Configure autofs
  ansible.builtin.import_role:
    name: autofs

- name: Mount /scratch/shared
  ansible.posix.mount:
    src: "slurm-nfs-node-0:/scratch/shared"
    path: /scratch/shared
    opts: rw,sync,soft
    state: mounted
    fstype: nfs
  when: "{{ (hostvars['slurm-nfs-node-0'].disk_count | int) > 0 }}"

- name: Install slurm conf
  ansible.builtin.import_role:
    name: slurm_conf
