- name: Ensure NVMe and RAID tools are installed
  ansible.builtin.apt:
    name:
      - nvme-cli
      - mdadm
    state: present
    update_cache: true 

- name: Ensure custom facts directory exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: '0755'

- name: Deploy custom NVMe fact script
  ansible.builtin.copy:
    src: nvme.fact  # Path to the script on your Ansible controller
    dest: /etc/ansible/facts.d/nvme.fact
    owner: root
    group: root
    mode: '0755'

- name: Re-gather facts to find the new custom fact
  ansible.builtin.setup: