- hosts: all
  remote_user: ubuntu
  become: yes
  roles:
    - name: user
      vars:
        user_name: tbarrett2
        user_uid: 1002
        user_ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIjPRr0iVR4mgzJy0ehnM5hWX4O86hM1bVTgdi5g3nkZ tbarrett@crusoeenergy.com"
