- name: Configure autofs
  ansible.builtin.import_role:
    name: autofs
  
- name: Install dependencies
  ansible.builtin.apt:
    name: nfs-common

- name: Install override.conf
  ansible.builtin.template:
    src: override.conf
    dest: /etc/systemd/system/slurmctld.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Mount /var/spool/slurmctld
  ansible.posix.mount:
    src: "slurm-nfs-node-0:/var/spool/slurmctld"
    path: /var/spool/slurmctld
    opts: rw,sync,soft
    state: mounted
    fstype: nfs

- name: Install slurm conf
  ansible.builtin.import_role:
    name: slurm_conf

- name: Restart slurmctld
  ansible.builtin.systemd_service:
    name: slurmctld
    state: restarted
    enabled: true
    daemon_reload: true
